all:
	arm-linux-gnueabihf-gcc hello_world.c -o hello_world

recv:
	arm-linux-gnueabihf-gcc recv.c -o recv

test:
	arm-linux-gnueabihf-gcc test.c -o test

per:
	arm-linux-gnueabihf-gcc performance.c -o performance